### ISSUE TITLE
Android wallet in full-screen, problem with "notch"

### ISSUE THREAD

**Issue by svartfogel** [Loopring/loopring-wallet-feedback#163]
Hi, Having some issues using the Loopring Wallet v 2.1.2.178 on Google Pixel 3XL. When using the wallet-app some of the top buttons is hard to reach due to the notch on the phone. Probably only an issue on phones with notches. https://discord.com/channels/488848270525857792/700743843921920073/935923908220186624

**Comment by Spconnol** [comment]
Not sure why this is closed on anyones. Pixel 5 cutout still covers the buttons. I cannot click them even with the extra 2 pixels or something it looks like was added. This is crazy to have this be around for so many months and be such a simple fix. Man put a wallet connect button in the profile to pull up the camera. Move the icons down even with your account balance but leave them floating right. C'mon. For the love of  goodness  please help all of us who cant connect to things because of this.

**Comment by odesium** [comment]
GUI updated in April
