### ISSUE TITLE
Allow user to update their details in case of change

### ISSUE THREAD

**Issue by odesium** [Loopring/loopring-wallet-feedback#65]
Under My Account, there should be an option to update Mobile or Email address in case these change so that the Loopring Guardian will have up to date details for wallet recovery or other approvals.

**Comment by a-triant** [comment]
+1 for that, otherwise at least should be a bold note at creation, that it cannot changed later so the users will pick carefully what to enter.

Myself I want to change to my secondary phone number which I don't share everywhere. Also I don't like the way if I change the phone number permanently which will have no more access but it will still be binded with my wallet.

**Comment by rmikedown** [comment]
Another +1 from me. I got burned on this pretty hard because I thought I was going to be adding both phone number and email, and then only later realized I couldn't change it. So now that I'm moving overseas I am probably going to have to completely abandon my wallet I paid 50 bucks for unless engineers add an option to add email or change phone number

**Comment by tommueller** [comment]
This :+1: 
You cannot expect users to use the same email / phonenumber for the rest of their lifes if they want to use your product safely ...

**Comment by LoopLotus** [comment]
This! Changing phone- and email-information needs to be a wallet feature.

**Comment by eyfung** [comment]
It's

**Comment by eyfung** [comment]
Is this feature added to the wallet yet, I'm moving overseas and wish to change my phone number as well

**Comment by ablankstory** [comment]
This is now available with 2FA.
